#!/usr/bin/env bash
set -euo pipefail

# ---------------------------------------------------------------------------
# start-tunnel.sh — Expose local SpacetimeDB + Vite to external players
#
# Prerequisites:
#   1. devtunnel CLI installed  (done automatically in post-create.sh)
#   2. Logged in:  devtunnel user login -g -d   (one-time, uses GitHub)
#   3. SpacetimeDB running on port 3000
#   4. Vite dev server running on port 5173
# ---------------------------------------------------------------------------

STDB_PORT=3000
VITE_PORT=5173
ENV_FILE="multi-snake/.env.tunnel"

# --- Preflight checks ------------------------------------------------------
if ! command -v devtunnel &>/dev/null; then
  echo "ERROR: devtunnel CLI not found. Run:  curl -sL https://aka.ms/DevTunnelCliInstall | bash"
  exit 1
fi

if ! devtunnel user show &>/dev/null; then
  echo "ERROR: Not logged in to Dev Tunnels."
  echo "Run:   devtunnel user login -g -d"
  echo "(Use -g for GitHub, -d for device-code flow in headless containers)"
  exit 1
fi

# --- Create a persistent tunnel with anonymous access -----------------------
echo "==> Creating dev tunnel..."
TUNNEL_ID=$(devtunnel create --allow-anonymous --expiration 1d | grep -oP 'Tunnel ID[:\s]+\K\S+' || true)

if [ -z "$TUNNEL_ID" ]; then
  # Fallback: parse from 'devtunnel show'
  TUNNEL_ID=$(devtunnel show 2>/dev/null | grep -oP 'Tunnel ID[:\s]+\K\S+' || true)
fi

if [ -z "$TUNNEL_ID" ]; then
  echo "ERROR: Could not determine tunnel ID. Check 'devtunnel create' output."
  exit 1
fi

echo "==> Tunnel ID: $TUNNEL_ID"

# --- Add ports --------------------------------------------------------------
devtunnel port create "$TUNNEL_ID" -p "$STDB_PORT"  --protocol http 2>/dev/null || true
devtunnel port create "$TUNNEL_ID" -p "$VITE_PORT"  --protocol http 2>/dev/null || true

# --- Derive public URLs (standard devtunnels.ms format) ---------------------
# The actual region is determined at host time; we extract from host output below.
echo ""
echo "==> Starting tunnel host..."
echo "    Press Ctrl+C to stop and delete the tunnel."
echo ""

# We need to capture the host output to extract URLs, but also keep it running.
# Strategy: start host in background, wait for URLs, then foreground it.
FIFO=$(mktemp -u)
mkfifo "$FIFO"

cleanup() {
  rm -f "$FIFO" "$ENV_FILE"
  devtunnel delete "$TUNNEL_ID" -f &>/dev/null || true
  echo ""
  echo "==> Tunnel $TUNNEL_ID deleted."
}
trap cleanup EXIT INT TERM

devtunnel host "$TUNNEL_ID" > "$FIFO" 2>&1 &
HOST_PID=$!

# Read output lines until we find the port URLs (timeout after 30s)
STDB_URL=""
VITE_URL=""
TIMEOUT=30
while IFS= read -r -t "$TIMEOUT" line; do
  echo "$line"
  # Match lines like: "Hosting port 3000 at https://..., https://TUNNELID-3000.REGION.devtunnels.ms/"
  if [[ "$line" =~ https://[a-z0-9-]+-${STDB_PORT}[^[:space:]]+ ]]; then
    STDB_URL="${BASH_REMATCH[0]}"
    STDB_URL="${STDB_URL%/}"  # trim trailing slash
  fi
  if [[ "$line" =~ https://[a-z0-9-]+-${VITE_PORT}[^[:space:]]+ ]]; then
    VITE_URL="${BASH_REMATCH[0]}"
    VITE_URL="${VITE_URL%/}"
  fi
  # Stop reading once both URLs are found or the host says "Ready"
  if [[ -n "$STDB_URL" && -n "$VITE_URL" ]] || [[ "$line" == *"Ready to accept"* ]]; then
    break
  fi
done < "$FIFO"

# Convert https:// to wss:// for the SpacetimeDB WebSocket connection
STDB_WS_URL="${STDB_URL/https:\/\//wss:\/\/}"

# --- Write .env.tunnel for Vite ---------------------------------------------
cat > "$ENV_FILE" <<EOF
# Auto-generated by start-tunnel.sh — do not commit
VITE_SPACETIMEDB_HOST=$STDB_WS_URL
VITE_SPACETIMEDB_DB_NAME=multi-snake
EOF

echo ""
echo "==========================================================="
echo "  Dev Tunnel is LIVE"
echo "==========================================================="
echo ""
echo "  Game URL (share this!):  $VITE_URL"
echo "  SpacetimeDB endpoint:    $STDB_WS_URL"
echo ""
echo "  .env.tunnel written to:  $ENV_FILE"
echo ""
echo "  Next: restart Vite in tunnel mode so it picks up the tunnel URL:"
echo "    cd multi-snake && npx vite --mode tunnel"
echo ""
echo "==========================================================="
echo ""

# Keep the tunnel host running in the foreground
wait "$HOST_PID"
