// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ChangeDirectionReducer from "../change_direction_reducer";
import JoinGameReducer from "../join_game_reducer";
import RestartGameReducer from "../restart_game_reducer";
import StartGameReducer from "../start_game_reducer";

export type ChangeDirectionParams = __Infer<typeof ChangeDirectionReducer>;
export type JoinGameParams = __Infer<typeof JoinGameReducer>;
export type RestartGameParams = __Infer<typeof RestartGameReducer>;
export type StartGameParams = __Infer<typeof StartGameReducer>;

