// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  hostIdentity: __t.identity().name("host_identity"),
  phase: __t.string(),
  gridSize: __t.u32().name("grid_size"),
  rngState: __t.u64().name("rng_state"),
  playerCount: __t.u32().name("player_count"),
});
