// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  Position,
} from "./types";


export default __t.row({
  identity: __t.identity().primaryKey(),
  gameId: __t.u64().name("game_id"),
  name: __t.string(),
  direction: __t.string(),
  nextDirection: __t.string().name("next_direction"),
  nextDirection2: __t.string().name("next_direction_2"),
  alive: __t.bool(),
  score: __t.u32(),
  color: __t.string(),
  get segments() {
    return __t.array(Position);
  },
  joinOrder: __t.u32().name("join_order"),
});
