export const styles = {
  page: {
    height: "100%",
    background: "#0f0f23",
    color: "#ccc",
    fontFamily: "'Segoe UI', system-ui, sans-serif",
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    padding: "1rem",
    overflow: "auto",
  },
  title: {
    fontSize: "2.5rem",
    fontWeight: 700,
    color: "#00cc00",
    margin: "0 0 0.5rem",
    letterSpacing: "0.05em",
  },
  subtitle: {
    color: "#888",
    margin: "0 0 2rem",
    fontSize: "0.9rem",
  },
  card: {
    background: "#1a1a2e",
    borderRadius: "12px",
    padding: "2rem",
    minWidth: "320px",
    maxWidth: "420px",
    width: "100%",
    boxShadow: "0 4px 24px rgba(0,0,0,0.4)",
  },
  input: {
    width: "100%",
    padding: "0.75rem 1rem",
    fontSize: "1rem",
    border: "2px solid #2a2a4a",
    borderRadius: "8px",
    background: "#16213e",
    color: "#eee",
    outline: "none",
    boxSizing: "border-box" as const,
    marginBottom: "1rem",
  },
  btnPrimary: {
    width: "100%",
    padding: "0.75rem 1.5rem",
    fontSize: "1rem",
    fontWeight: 600,
    border: "none",
    borderRadius: "8px",
    background: "#00cc00",
    color: "#0f0f23",
    cursor: "pointer",
  },
  btnSecondary: {
    padding: "0.6rem 1.5rem",
    fontSize: "0.9rem",
    fontWeight: 600,
    border: "2px solid #00cc00",
    borderRadius: "8px",
    background: "transparent",
    color: "#00cc00",
    cursor: "pointer",
  },
  btnDanger: {
    padding: "0.6rem 1.5rem",
    fontSize: "0.9rem",
    fontWeight: 600,
    border: "2px solid #e74c3c",
    borderRadius: "8px",
    background: "transparent",
    color: "#e74c3c",
    cursor: "pointer",
  },
  playerList: {
    listStyle: "none",
    padding: 0,
    margin: "1rem 0",
  },
  playerItem: {
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
    padding: "0.5rem 0",
    fontSize: "1rem",
  },
  colorDot: (color: string) => ({
    width: "12px",
    height: "12px",
    borderRadius: "50%",
    background: color,
    flexShrink: 0,
  }),
  badge: {
    fontSize: "0.7rem",
    background: "#f39c12",
    color: "#0f0f23",
    padding: "2px 6px",
    borderRadius: "4px",
    fontWeight: 700,
  },
  gameLayout: {
    display: "flex",
    gap: "1.5rem",
    alignItems: "flex-start",
    flexWrap: "wrap" as const,
    justifyContent: "center",
  },
  scoreboard: {
    background: "#1a1a2e",
    borderRadius: "12px",
    padding: "1rem 1.5rem",
    minWidth: "180px",
  },
  scoreRow: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    padding: "0.35rem 0",
    fontSize: "0.9rem",
  },
  canvas: {
    borderRadius: "8px",
    border: "2px solid #2a2a4a",
  },
  deadLabel: {
    color: "#666",
    fontSize: "0.75rem",
    marginLeft: "4px",
  },
  lobbyRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "0.75rem 1rem",
    background: "#16213e",
    borderRadius: "8px",
    marginBottom: "0.5rem",
  },
} as const;
